sudo: required
services:
  - docker
before_install:
  - docker build -t smaharnoor/shivcicd:v1.0 .
script:
  - echo "$password" | docker login -u "$username" --password-stdin
  - docker images
  - docker push smaharnoor/shivcicd:v1.0
notifications:
  email:
    recipients:
      - shiv.maharnoor@gmail.com
    on_success: always
    on_failure: always
